#!/bin/python3

import os
import sys
import itertools

def getMoneySpent(keyboards, drives, b):
    
    lis=list(itertools.product(keyboards,drives))
    c=-1
    for i,j in lis:  
        if (i+j)<=b:
            if (i+j)>c:
                c=i+j
    

    return c
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    b,n,m = map(int,input().rstrip().split())
    keyboards = list(map(int, input().rstrip().split()))

    drives = list(map(int, input().rstrip().split()))
    # The maximum amount of money she can spend on a keyboard and USB drive, or -1 if she can't purchase both items
    moneySpent = getMoneySpent(keyboards, drives, b)

    fptr.write(str(moneySpent) + '\n')

    fptr.close()
